name: '$(BuildDefinitionName).$(DayOfYear)$(Rev:.r)'

trigger: none

pr: none

pool:
  vmImage: 'ubuntu-20.04'

variables:
- name:  'workingDirectory'
  value: 'src/app/ReactFlowTest'

stages:

- stage: buildApp
  displayName: 'Build application'
  jobs:
    - job: appBuild
      displayName: 'Build application'
      workingDirectory: '$(workingDirectory)'
      steps:
      - checkout: self # checkout github repository

      - task: PowerShell@2
        displayName: 'Yarn install'
        inputs:
          targetType: inline
          script: |
            yarn install

      - task: PowerShell@2
        displayName: 'Yarn install'
        inputs:
          targetType: inline
          script: |
            yarn build